package de.janchristoph.soccer.model;

public enum FlagType {
	TOP_LEFT_50, TOP_LEFT_40, TOP_LEFT_30, TOP_LEFT_20, TOP_LEFT_10,

	TOP_0,

	TOP_RIGHT_10, TOP_RIGHT_20, TOP_RIGHT_30, TOP_RIGHT_40, TOP_RIGHT_50,

	LEFT_TOP, CENTER_TOP, RIGHT_TOP,
	
	LEFT_TOP_30, LEFT_TOP_20, LEFT_TOP_10,
	
	RIGHT_TOP_30, RIGHT_TOP_20, RIGHT_TOP_10,
	
	LEFT_0,
	
	RIGHT_0,

	GOAL_LEFT_TOP, GOAL_LEFT, GOAL_LEFT_BOTTOM,

	PENALTY_LEFT_TOP, PENALTY_LEFT_CENTER, PENALTY_LEFT_BOTTOM,

	CENTER,

	PENALTY_RIGHT_TOP, PENALTY_RIGHT_CENTER, PENALTY_RIGHT_BOTTOM,

	GOAL_RIGHT_TOP, GOAL_RIGHT, GOAL_RIGHT_BOTTOM,
	
	LEFT_BOTTOM_10, LEFT_BOTTOM_20, LEFT_BOTTOM_30,
	
	RIGHT_BOTTOM_10, RIGHT_BOTTOM_20, RIGHT_BOTTOM30,

	LEFT_BOTTOM, CENTER_BOTTOM, RIGHT_BOTTOM,

	BOTTOM_LEFT_50, BOTTOM_LEFT_40, BOTTOM_LEFT_30, BOTTOM_LEFT_20, BOTTOM_LEFT_10,

	BOTTOM_0,

	BOTTOM_RIGHT_10, BOTTOM_RIGHT_20, BOTTOM_RIGHT_30, BOTTOM_RIGHT_40, BOTTOM_RIGHT_50
}
