package de.janchristoph.soccer.model;

public enum FlagType {
	TOP_LEFT_50, TOP_LEFT_40, TOP_LEFT_30, TOP_LEFT_20, TOP_LEFT_10,

	TOP_0,

	TOP_RIGHT_10, TOP_RIGHT_20, TOP_RIGHT_30, TOP_RIGHT_40, TOP_RIGHT_50,

	LEFT_TOP, CENTER_TOP, RIGHT_TOP,

	LEFT,

	GOAL_LEFT_TOP, GOAL_LEFT, GOAL_LEFT_BOTTOM,

	PENALITY_LEFT_TOP, PENALITY_LEFT_CENTER, PENALITY_LEFT_BOTTOM,

	CENTER,

	PENALITY_RIGHT_TOP, PENALITY_RIGHT_CENTER, PENALITY_RIGHT_BOTTOM,

	GOAL_RIGHT_TOP, GOAL_RIGHT, GOAL_RIGHT_BOTTOM,

	RIGHT,

	LEFT_BOTTOM, CENTER_BOTTOM, RIGHT_BOTTOM,

	BOTTOM_LEFT_50, BOTTOM_LEFT_40, BOTTOM_LEFT_30, BOTTOM_LEFT_20, BOTTOM_LEFT_10,

	BOTTOM_0,

	BOTTOM_RIGHT_10, BOTTOM_RIGHT_20, BOTTOM_RIGHT_30, BOTTOM_RIGHT_40, BOTTOM_RIGHT_50
}
